sudo: false

language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_script:
  - coverage=OFF
  - if [ "$CXX" = "g++" ]; then
        export CXX="g++-4.8" CC="gcc-4.8";
        if [ $TRAVIS_OS_NAME = linux ]; then coverage=ON; fi
    fi

script: scons